# 
#
[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
source ~/.config/nvim/plugin/molokai.rc.vim
'''

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
source ~/.config/nvim/plugin/vim-anzu.rc.vim
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['vim-anzu']
hook_add = '''
source ~/.config/nvim/plugin/lightline.rc.vim
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'


[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add = '''
source ~/.config/nvim/plugin/rust.rc.vim
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
#depends = ['LanguageClient-neovim']
depends = ['context_filetype.vim']
hook_add = '''
source ~/.config/nvim/plugin/deoplete.rc.vim
'''

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
hook_add = '''
source ~/.config/nvim/plugin/LanguageClient-neovim.rc.vim
'''

