# [[plugins]]
# repo = 'Shougo/context_filetype.vim'


# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# if = 'has("nvim")'
# on_i = 1
# hook_add = '''
# source ~/.config/nvim/plugin/deoplete.rc.vim
# '''

# [[plugins]]
# repo = 'autozimu/LanguageClient-neovim'
# rev = 'next'
# build = 'bash install.sh'
# depends = ['deoplete.nvim']
# on_i = 1
# hook_add = '''
# source ~/.config/nvim/plugin/LanguageClient-neovim.rc.vim
# '''

# [[plugins]]
# repo = 'rust-lang/rust.vim'
# on_ft = 'rust'
# on_i = 1
# hook_add = '''
# source ~/.config/nvim/plugin/rust.rc.vim
# '''

# [[plugins]]
# repo = 'Shougo/neosnippet'
# on_i  = 1
# on_ft = ['snippet']
# depends = ['neosnippet-snippets']
# hook_source = '''
#   imap <C-k> <Plug>(neosnippet_expand_or_jump)
#   smap <C-k> <Plug>(neosnippet_expand_or_jump)
#   xmap <C-k> <Plug>(neosnippet_expand_target)
#   if has('conceal')
#     set conceallevel=2 concealcursor=niv
#   endif
# '''
# 
# [[plugins]]
# repo = 'Shougo/neosnippet-snippets'
# 
# [[plugins]]
# repo = 'rust-lang/rust.vim'
# on_i = 1
# on_ft = 'rust'
# hook_add = '''
# source ~/.config/nvim/plugin/rust.rc.vim
# '''

